export type Language = "en" | "es" | "ar" | "te";

export const languageNames: Record<Language, string> = { en: "English", es: "Español", ar: "العربية", te: "తెలుగు" };

const strings = {
  en: { dashboard: "Confirmed dashboard", title: "Your report at a glance", bodyMap: "Body map", selected: "Selected", confirmed: "Confirmed tests", inRange: "In range", outside: "Outside range", withoutRange: "Without range", all: "All", high: "High", low: "Low", noRange: "No range", search: "Search tests", learn: "Learn & ask", evidence: "Evidence", askReport: "Ask report", review: "Review data", healthRating: "Health rating", ratingNote: "Range-based summary, not a diagnosis", nearbyCare: "Nearby care", normalRange: "Normal range", yourValue: "Your value", educationalOnly: "Educational information only — not a diagnosis or treatment recommendation.", whatItIs: "What it is", whyChecked: "Why it is checked", outsideMeaning: "When it is outside the range", askAbout: "Ask about", reportAssistant: "Confirmed report assistant", askClarity: "Ask Clarity", confirmedResults: "confirmed results", outsideListed: "outside listed ranges", reportIntro: "Ask about patterns across your confirmed results. I can explain what is present in this report, but I cannot diagnose a condition or replace a healthcare professional.", language: "Language" },
  es: { dashboard: "Panel confirmado", title: "Tu informe de un vistazo", bodyMap: "Mapa corporal", selected: "Seleccionado", confirmed: "Pruebas confirmadas", inRange: "En rango", outside: "Fuera de rango", withoutRange: "Sin rango", all: "Todas", high: "Alto", low: "Bajo", noRange: "Sin rango", search: "Buscar pruebas", learn: "Aprender y preguntar", evidence: "Evidencia", askReport: "Preguntar sobre el informe", review: "Revisar datos", healthRating: "Puntuación de salud", ratingNote: "Resumen basado en rangos, no es un diagnóstico", nearbyCare: "Atención cercana", normalRange: "Rango normal", yourValue: "Tu valor", educationalOnly: "Información educativa solamente; no es diagnóstico ni recomendación de tratamiento.", whatItIs: "Qué es", whyChecked: "Por qué se analiza", outsideMeaning: "Cuando está fuera del rango", askAbout: "Preguntar sobre", reportAssistant: "Asistente del informe confirmado", askClarity: "Pregúntale a Clarity", confirmedResults: "resultados confirmados", outsideListed: "fuera de los rangos indicados", reportIntro: "Pregunta sobre patrones en tus resultados confirmados. Puedo explicar lo que aparece en el informe, pero no diagnosticar ni sustituir a un profesional.", language: "Idioma" },
  ar: { dashboard: "لوحة النتائج المؤكدة", title: "تقريرك بنظرة سريعة", bodyMap: "خريطة الجسم", selected: "المحدد", confirmed: "الفحوصات المؤكدة", inRange: "ضمن النطاق", outside: "خارج النطاق", withoutRange: "دون نطاق", all: "الكل", high: "مرتفع", low: "منخفض", noRange: "دون نطاق", search: "بحث في الفحوصات", learn: "تعلّم واسأل", evidence: "الدليل", askReport: "اسأل عن التقرير", review: "مراجعة البيانات", healthRating: "التقييم الصحي", ratingNote: "ملخص مبني على النطاقات وليس تشخيصاً", nearbyCare: "رعاية قريبة", normalRange: "النطاق الطبيعي", yourValue: "قيمتك", educationalOnly: "معلومات تعليمية فقط، وليست تشخيصاً أو توصية علاجية.", whatItIs: "ما هو", whyChecked: "لماذا يُفحص", outsideMeaning: "عندما يكون خارج النطاق", askAbout: "اسأل عن", reportAssistant: "مساعد التقرير المؤكد", askClarity: "اسأل كلاريتي", confirmedResults: "نتائج مؤكدة", outsideListed: "خارج النطاقات المذكورة", reportIntro: "اسأل عن الأنماط في نتائجك المؤكدة. يمكنني شرح ما ورد في التقرير، لكن لا يمكنني التشخيص أو استبدال المختص.", language: "اللغة" },
  te: { dashboard: "ధృవీకరించిన డ్యాష్‌బోర్డ్", title: "మీ నివేదిక ఒక చూపులో", bodyMap: "శరీర పటం", selected: "ఎంచుకున్నది", confirmed: "ధృవీకరించిన పరీక్షలు", inRange: "పరిధిలో", outside: "పరిధి వెలుపల", withoutRange: "పరిధి లేదు", all: "అన్నీ", high: "ఎక్కువ", low: "తక్కువ", noRange: "పరిధి లేదు", search: "పరీక్షలను వెతకండి", learn: "తెలుసుకోండి & అడగండి", evidence: "ఆధారం", askReport: "నివేదికను అడగండి", review: "డేటాను సమీక్షించండి", healthRating: "ఆరోగ్య రేటింగ్", ratingNote: "పరిధుల ఆధారిత సారాంశం, నిర్ధారణ కాదు", nearbyCare: "సమీప వైద్యం", normalRange: "సాధారణ పరిధి", yourValue: "మీ విలువ", educationalOnly: "విద్యా సమాచారం మాత్రమే — నిర్ధారణ లేదా చికిత్స సిఫార్సు కాదు.", whatItIs: "ఇది ఏమిటి", whyChecked: "ఎందుకు పరీక్షిస్తారు", outsideMeaning: "పరిధి వెలుపల ఉన్నప్పుడు", askAbout: "దీని గురించి అడగండి", reportAssistant: "ధృవీకరించిన నివేదిక సహాయకుడు", askClarity: "క్లారిటీని అడగండి", confirmedResults: "ధృవీకరించిన ఫలితాలు", outsideListed: "పేర్కొన్న పరిధుల వెలుపల", reportIntro: "మీ ధృవీకరించిన ఫలితాలలో నమూనాల గురించి అడగండి. నివేదికలో ఉన్నదాన్ని వివరించగలను, కానీ నిర్ధారణ చేయలేను.", language: "భాష" },
} satisfies Record<Language, Record<string, string>>;

export type TranslationKey = keyof typeof strings.en;
export function translate(language: Language, key: TranslationKey): string { return strings[language][key] ?? strings.en[key]; }
export function languageDirection(language: Language): "rtl" | "ltr" { return language === "ar" ? "rtl" : "ltr"; }